Update deploy-pygame.yml

diff --git a/.github/workflows/deploy-pygame.yml b/.github/workflows/deploy-pygame.yml
--- a/.github/workflows/deploy-pygame.yml
+++ b/.github/workflows/deploy-pygame.yml
@@ -20,7 +20,7 @@ jobs:
     - name: Build the game
       run: |
         echo "Attempting to build the game"
-        python -m pygbag --build $GITHUB_WORKSPACE/main.py --gui || { echo "Build failed"; exit 1; }
+        python -m pygbag --build $GITHUB_WORKSPACE/main.py || { echo "Build failed"; exit 1; }
         echo "Successfully built the game and compiled to WebAssembly"
     - name: "Upload to GitHub pages branch gh-pages"
       uses: JamesIves/github-pages-deploy-action@4.1.7
